"""Modèle ORM SQLAlchemy 2.0 pour la table predictions.

⚠️ FICHIER AUTO-GÉNÉRÉ — NE PAS ÉDITER À LA MAIN.
Régénérer via : uv run python scripts/generate_prediction_model.py

Source des features : api.schemas.PredictionInput
Mapping des noms   : api.feature_naming.to_sql_column_name
"""
from datetime import datetime

from sqlalchemy import DateTime, Boolean, Float, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column

from api.database import Base


class Prediction(Base):
    """Une prédiction enregistrée par l'endpoint POST /predict.

    Schéma à plat (une colonne par feature) pour permettre une lecture
    directe par Evidently à l'étape de monitoring (pas de transformation
    intermédiaire de JSON vers DataFrame).
    """

    __tablename__ = "predictions"

    # --- Identifiants ---
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    request_id: Mapped[str] = mapped_column(
        String(length=36), unique=True, index=True, nullable=False,
        comment="UUID de la requête, exposé au client pour traçabilité",
    )

    # --- Métadonnées ---
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        index=True,
        nullable=False,
        server_default=func.current_timestamp(),
        comment="Horodatage UTC de la prédiction",
    )
    model_version: Mapped[str] = mapped_column(
        String(length=32), index=True, nullable=False,
        comment="Version de l'API/modèle ayant produit la prédiction",
    )
    threshold: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="Seuil de décision F3 utilisé (issu du Projet 6)",
    )

    # --- Sortie du modèle ---
    prediction_proba: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="Probabilité prédite par XGBoost (classe 1 = défaut)",
    )
    prediction: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="Décision binaire (0 ou 1) après application du seuil",
    )

    # --- Features (auto-générées depuis schemas.py) ---
    NAME_CONTRACT_TYPE: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    CODE_GENDER: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    FLAG_OWN_CAR: Mapped[int | None] = mapped_column(Integer, nullable=True)
    FLAG_OWN_REALTY: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AMT_INCOME_TOTAL: Mapped[float | None] = mapped_column(Float, nullable=True)
    AMT_CREDIT: Mapped[float | None] = mapped_column(Float, nullable=True)
    AMT_ANNUITY: Mapped[float | None] = mapped_column(Float, nullable=True)
    NAME_FAMILY_STATUS: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    REGION_POPULATION_RELATIVE: Mapped[float | None] = mapped_column(Float, nullable=True)
    DAYS_BIRTH: Mapped[float | None] = mapped_column(Float, nullable=True)
    DAYS_EMPLOYED: Mapped[float | None] = mapped_column(Float, nullable=True)
    DAYS_REGISTRATION: Mapped[float | None] = mapped_column(Float, nullable=True)
    DAYS_ID_PUBLISH: Mapped[float | None] = mapped_column(Float, nullable=True)
    FLAG_EMP_PHONE: Mapped[int | None] = mapped_column(Integer, nullable=True)
    FLAG_WORK_PHONE: Mapped[int | None] = mapped_column(Integer, nullable=True)
    FLAG_PHONE: Mapped[int | None] = mapped_column(Integer, nullable=True)
    CNT_FAM_MEMBERS: Mapped[int | None] = mapped_column(Integer, nullable=True)
    REGION_RATING_CLIENT_W_CITY: Mapped[int | None] = mapped_column(Integer, nullable=True)
    WEEKDAY_APPR_PROCESS_START: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    HOUR_APPR_PROCESS_START: Mapped[int | None] = mapped_column(Integer, nullable=True)
    REG_REGION_NOT_LIVE_REGION: Mapped[int | None] = mapped_column(Integer, nullable=True)
    LIVE_REGION_NOT_WORK_REGION: Mapped[int | None] = mapped_column(Integer, nullable=True)
    REG_CITY_NOT_LIVE_CITY: Mapped[int | None] = mapped_column(Integer, nullable=True)
    LIVE_CITY_NOT_WORK_CITY: Mapped[int | None] = mapped_column(Integer, nullable=True)
    EXT_SOURCE_2: Mapped[float | None] = mapped_column(Float, nullable=True)
    EXT_SOURCE_3: Mapped[float | None] = mapped_column(Float, nullable=True)
    OBS_60_CNT_SOCIAL_CIRCLE: Mapped[int | None] = mapped_column(Integer, nullable=True)
    DEF_60_CNT_SOCIAL_CIRCLE: Mapped[int | None] = mapped_column(Integer, nullable=True)
    DAYS_LAST_PHONE_CHANGE: Mapped[float | None] = mapped_column(Float, nullable=True)
    FLAG_DOCUMENT_3: Mapped[int | None] = mapped_column(Integer, nullable=True)
    FLAG_DOCUMENT_6: Mapped[int | None] = mapped_column(Integer, nullable=True)
    FLAG_DOCUMENT_8: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AMT_REQ_CREDIT_BUREAU_MON: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AMT_REQ_CREDIT_BUREAU_QRT: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AMT_REQ_CREDIT_BUREAU_YEAR: Mapped[int | None] = mapped_column(Integer, nullable=True)
    DAYS_EMPLOYED_ANOM: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    CREDIT_INCOME_PERCENT: Mapped[float | None] = mapped_column(Float, nullable=True)
    ANNUITY_INCOME_PERCENT: Mapped[float | None] = mapped_column(Float, nullable=True)
    CREDIT_TERM: Mapped[float | None] = mapped_column(Float, nullable=True)
    NAME_HOUSING_TYPE_GRP: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    NAME_EDUCATION_TYPE_GRP: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    NAME_INCOME_TYPE_GRP: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    NAME_TYPE_SUITE_GRP: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    ORG_GROUP: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    OCCUPATION_TYPE_GRP: Mapped[str | None] = mapped_column(String(length=64), nullable=True)
    BUREAU_DAYS_CREDIT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_CREDIT_DAY_OVERDUE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_CREDIT_DAY_OVERDUE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_CREDIT_DAY_OVERDUE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_ENDDATE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_ENDDATE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_ENDDATE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_ENDDATE_FACT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_ENDDATE_FACT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_ENDDATE_FACT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_MAX_OVERDUE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_MAX_OVERDUE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_MAX_OVERDUE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_CNT_CREDIT_PROLONG_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_CNT_CREDIT_PROLONG_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_CNT_CREDIT_PROLONG_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_DEBT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_DEBT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_DEBT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_LIMIT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_LIMIT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_LIMIT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_OVERDUE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_OVERDUE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_AMT_CREDIT_SUM_OVERDUE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_UPDATE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_UPDATE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_DAYS_CREDIT_UPDATE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAD_MAX_OVERDUE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAD_MAX_OVERDUE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAD_MAX_OVERDUE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAD_ENDDATE_FACT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAD_ENDDATE_FACT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAD_ENDDATE_FACT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_MIN_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_MIN_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_MIN_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_MAX_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_MAX_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_MAX_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_COUNT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_COUNT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_COUNT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_NO_DPD_COUNT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_NO_DPD_COUNT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_NO_DPD_COUNT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_DPD_COUNT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_DPD_COUNT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_DPD_COUNT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_UNKNOWN_COUNT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_UNKNOWN_COUNT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_STATUS_UNKNOWN_COUNT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_HISTORY_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_HISTORY_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_MONTHS_HISTORY_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_NO_DPD_RATIO_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_NO_DPD_RATIO_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_NO_DPD_RATIO_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_DPD_RATIO_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_DPD_RATIO_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_DPD_RATIO_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_UNKNOWN_RATIO_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_UNKNOWN_RATIO_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_BB_UNKNOWN_RATIO_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAS_CLOSED_CREDIT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAS_CLOSED_CREDIT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_HAS_CLOSED_CREDIT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_SK_ID_BUREAU_count: Mapped[float | None] = mapped_column(Float, nullable=True)
    BUREAU_CREDIT_ACTIVE_lambda: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: BUREAU_CREDIT_ACTIVE_<lambda>
    BUREAU_CREDIT_TYPE_nunique: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_min_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_min_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_min_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_size_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_size_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_BALANCE_size_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_min_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_min_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_min_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_min_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_min_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_CNT_INSTALMENT_FUTURE_min_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_sum_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_sum_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_sum_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_sum_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_sum_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_SK_DPD_DEF_sum_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_NAME_CONTRACT_STATUS_lambda_0_mean: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: POS_NAME_CONTRACT_STATUS_<lambda_0>_mean
    POS_NAME_CONTRACT_STATUS_lambda_0_max: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: POS_NAME_CONTRACT_STATUS_<lambda_0>_max
    POS_NAME_CONTRACT_STATUS_lambda_0_sum: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: POS_NAME_CONTRACT_STATUS_<lambda_0>_sum
    POS_NAME_CONTRACT_STATUS_lambda_1_mean: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: POS_NAME_CONTRACT_STATUS_<lambda_1>_mean
    POS_NAME_CONTRACT_STATUS_lambda_1_max: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: POS_NAME_CONTRACT_STATUS_<lambda_1>_max
    POS_NAME_CONTRACT_STATUS_lambda_1_sum: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: POS_NAME_CONTRACT_STATUS_<lambda_1>_sum
    POS_MONTHS_HISTORY_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_HISTORY_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_MONTHS_HISTORY_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_DPD_RATIO_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_DPD_RATIO_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_DPD_RATIO_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    POS_NB_CREDITS: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_min_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_min_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_min_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_size_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_size_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_MONTHS_BALANCE_size_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_BALANCE_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_BALANCE_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_BALANCE_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_BALANCE_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_BALANCE_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_BALANCE_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_CREDIT_LIMIT_ACTUAL_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_CREDIT_LIMIT_ACTUAL_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_CREDIT_LIMIT_ACTUAL_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_CREDIT_LIMIT_ACTUAL_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_CREDIT_LIMIT_ACTUAL_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_AMT_CREDIT_LIMIT_ACTUAL_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_sum_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_sum_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_sum_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_sum_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_sum_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_SK_DPD_DEF_sum_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_CREDIT_UTILIZATION_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_CREDIT_UTILIZATION_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_CREDIT_UTILIZATION_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_CREDIT_UTILIZATION_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_CREDIT_UTILIZATION_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_CREDIT_UTILIZATION_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_PAYMENT_RATIO_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_PAYMENT_RATIO_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_PAYMENT_RATIO_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_PAYMENT_RATIO_min_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_PAYMENT_RATIO_min_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_CC_PAYMENT_RATIO_min_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    CC_NB_CARDS: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_NUM_INSTALMENT_NUMBER_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_NUM_INSTALMENT_NUMBER_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_NUM_INSTALMENT_NUMBER_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_NUM_INSTALMENT_NUMBER_count_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_NUM_INSTALMENT_NUMBER_count_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_NUM_INSTALMENT_NUMBER_count_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_AMT_INSTALMENT_sum_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_AMT_INSTALMENT_sum_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_AMT_INSTALMENT_sum_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_AMT_PAYMENT_sum_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_AMT_PAYMENT_sum_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_AMT_PAYMENT_sum_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_min_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_min_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_min_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_PAYMENT_DIFF_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_DAYS_DELAY_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_DAYS_DELAY_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_DAYS_DELAY_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_DAYS_DELAY_max_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_DAYS_DELAY_max_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_DAYS_DELAY_max_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_IS_LATE_sum_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_IS_LATE_sum_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_IS_LATE_sum_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_IS_LATE_mean_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_IS_LATE_mean_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_INST_IS_LATE_mean_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    INST_NB_CREDITS: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_ANNUITY_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_ANNUITY_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_ANNUITY_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_APPLICATION_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_APPLICATION_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_APPLICATION_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_CREDIT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_CREDIT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_CREDIT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_DOWN_PAYMENT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_DOWN_PAYMENT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_DOWN_PAYMENT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_GOODS_PRICE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_GOODS_PRICE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_AMT_GOODS_PRICE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_HOUR_APPR_PROCESS_START_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_HOUR_APPR_PROCESS_START_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_HOUR_APPR_PROCESS_START_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_NFLAG_LAST_APPL_IN_DAY_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_NFLAG_LAST_APPL_IN_DAY_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_NFLAG_LAST_APPL_IN_DAY_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_RATE_DOWN_PAYMENT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_RATE_DOWN_PAYMENT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_RATE_DOWN_PAYMENT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_DECISION_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_DECISION_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_DECISION_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_SELLERPLACE_AREA_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_SELLERPLACE_AREA_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_SELLERPLACE_AREA_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_CNT_PAYMENT_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_CNT_PAYMENT_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_CNT_PAYMENT_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_FIRST_DRAWING_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_FIRST_DRAWING_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_FIRST_DRAWING_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_FIRST_DUE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_FIRST_DUE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_FIRST_DUE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_LAST_DUE_1ST_VERSION_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_LAST_DUE_1ST_VERSION_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_LAST_DUE_1ST_VERSION_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_LAST_DUE_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_LAST_DUE_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_LAST_DUE_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_TERMINATION_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_TERMINATION_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_DAYS_TERMINATION_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_NFLAG_INSURED_ON_APPROVAL_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_NFLAG_INSURED_ON_APPROVAL_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_NFLAG_INSURED_ON_APPROVAL_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_PREV_CREDIT_DIFF_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_PREV_CREDIT_DIFF_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_PREV_CREDIT_DIFF_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_PREV_CREDIT_RATIO_mean: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_PREV_CREDIT_RATIO_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_PREV_CREDIT_RATIO_sum: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_SK_ID_PREV_count: Mapped[float | None] = mapped_column(Float, nullable=True)
    PREV_NAME_CONTRACT_STATUS_lambda_0: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: PREV_NAME_CONTRACT_STATUS_<lambda_0>
    PREV_NAME_CONTRACT_STATUS_lambda_1: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: PREV_NAME_CONTRACT_STATUS_<lambda_1>
    PREV_NAME_CONTRACT_STATUS_lambda_2: Mapped[float | None] = mapped_column(Float, nullable=True)  # original: PREV_NAME_CONTRACT_STATUS_<lambda_2>
    PREV_APPROVAL_RATIO: Mapped[float | None] = mapped_column(Float, nullable=True)
    def __repr__(self) -> str:
        return (
            f"<Prediction id={self.id} request_id={self.request_id} "
            f"proba={self.prediction_proba:.4f} pred={self.prediction}>"
        )
